describe('My First Test', function() {
  it('Visits the Home Page', function() {
    cy.visit('http://localhost:3000/')
    cy.contains('To Do')
    cy.get('#new-item')
    .type('learn cypress')
    .should('have.value', 'learn cypress')
    cy.get('#tags')
    .type('js, test')
    .should('have.value', 'js, test')
    cy.contains('+').click()
    cy.contains('learn cypress').should('exist')
    cy.get('#search')
    .type('cat')
    cy.contains('learn cypress').should('not.exist')
    cy.get('#search')
    .type('{backspace}{backspace}{backspace}learn')
    cy.contains('learn cypress').should('exist')
    cy.get('#delete').click()
    cy.contains('learn cypress').should('not.exist')
  })
})